---
apiVersion: v1
kind: List
items:
- apiVersion: v1
  kind: Service
  metadata:
    annotations:
      prometheus.io/port: "9779"
      prometheus.io/scrape: "true"
    labels:
      app: awda-middleware
      provider: fabric8
      version: 4.4.0
      group: org.mycompany
    name: awda-middleware
  spec:
    ports:
    - name: msgsrvr
      port: 8787
      protocol: TCP
      targetPort: 8787
    selector:
      app: awda-middleware
      provider: fabric8
      group: org.mycompany
- apiVersion: apps/v1
  kind: Deployment
  metadata:
    labels:
      app: awda-middleware
      provider: fabric8
      version: 4.4.0
      group: org.mycompany
    name: awda-middleware
  spec:
    replicas: 1
    revisionHistoryLimit: 2
    selector:
      matchLabels:
        app: awda-middleware
        provider: fabric8
        group: org.mycompany
    template:
      metadata:
        labels:
          app: awda-middleware
          provider: fabric8
          version: 4.4.0
          group: org.mycompany
      spec:
        containers:
        - env:
          - name: SPRING_APPLICATION_JSON
            value: '{"server":{"tomcat":{"max-threads":1}}}'
          - name: KUBERNETES_NAMESPACE
            valueFrom:
              fieldRef:
                fieldPath: metadata.namespace
          image: mycompany/awda-middleware:4.4.0
          imagePullPolicy: IfNotPresent
          livenessProbe:
            failureThreshold: 3
            httpGet:
              path: /health
              port: 8081
              scheme: HTTP
            initialDelaySeconds: 180
            successThreshold: 1
          name: spring-boot
          ports:
          - containerPort: 8787
            name: msgsrvr
            protocol: TCP
          - containerPort: 9779
            name: prometheus
            protocol: TCP
          - containerPort: 8778
            name: jolokia
            protocol: TCP
          readinessProbe:
            failureThreshold: 3
            httpGet:
              path: /health
              port: 8081
              scheme: HTTP
            initialDelaySeconds: 10
            successThreshold: 1
          resources:
            limits:
              cpu: "1.0"
            requests:
              cpu: "0.2"
          securityContext:
            privileged: false
